# Kahoot: Energy Spain 2021

Apuntes: https://datons.craft.me/h3f5pSQSE7l6RW/b/78DCF9D7-6C95-453E-90BC-09AB176F71F4/df.groupby()-Categorical-Columns-to-

In [5]:
import pandas as pd

df = pd.read_csv('energy_2021.csv')
df

              technology  year  month  day  hour  generation_mwh
0                 Carbon  2019      1    1     0          1867.0
1                 Carbon  2019      1    1     1          1618.0
2                 Carbon  2019      1    1     2          1535.3
3                 Carbon  2019      1    1     3          1344.0
4                 Carbon  2019      1    1     4          1345.0
...                  ...   ...    ...  ...   ...             ...
368251  Other Renewables  2021     12   31    19           602.7
368252  Other Renewables  2021     12   31    20           608.2
368253  Other Renewables  2021     12   31    21           606.7
368254  Other Renewables  2021     12   31    22           607.5
368255  Other Renewables  2021     12   31    23           591.6

[368256 rows x 6 columns]